# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text = QtWidgets.QRadioButton(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(170, 240, 131, 51))
        self.text.setObjectName("text")
        self.image = QtWidgets.QRadioButton(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(320, 240, 141, 51))
        self.image.setObjectName("image")
        self.sound = QtWidgets.QRadioButton(self.centralwidget)
        self.sound.setGeometry(QtCore.QRect(494, 239, 81, 51))
        self.sound.setObjectName("sound")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 130, 151, 71))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 350, 93, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text.setText(_translate("MainWindow", "Текст"))
        self.image.setText(_translate("MainWindow", "Изображения"))
        self.sound.setText(_translate("MainWindow", "Звук"))
        self.label.setText(_translate("MainWindow", "Choose your fighter"))
        self.pushButton.setText(_translate("MainWindow", "Выбрать"))
